### ISSUE TITLE
Problem with SUMO versions

### ISSUE THREAD

**Issue by lcipolina** [susomena/PERMIT#2]
Hi, thank you very much for developing this library. I am planning to use it for my research. However I have a problem with SUMO versions.

The issue is that Sumo-Plexe requires a really old SUMO version (0.32), while I need to have SUMO 1.6 (the latest) on my machine since I use SUMO with CARLA integration. Plexe won't run on SUMO 1.6, I've tried.

**Question: Is there a way to have both SUMO versions installed on my machine without conflict? 
Otherwise, maybe how can I upgrade the library to be compatible with the latest SUMO?**

Thanks!

**Comment by susomena** [comment]
Hi, Lucia,

You can have more than one SUMO version installed in the same computer (different directories) without any conflict. You just need to declare the SUMO_HOME environment variable and make it point to the directory of the SUMO version you need at any time. For example, when you want to use PERMIT you have to make it point to the directory of the 0.31.0 version (not the 0.32.0 version, be careful because I think PERMIT won't work with 0.32.0), but when you want to use CARLA, just change the SUMO_HOME variable to point to the SUMO 1.6 version.

PERMIT can only be used with Plexe-SUMO (Plexe-SUMO has some features that are not included in standard SUMO versions and PERMIT uses them), so you could only change PERMIT to make it compatible with newer versions of Plexe-SUMO, but not newer versions of SUMO.
